# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6275aeef583f61e92548ffc5aa6f04ae469716e1d4e0c101f7141a6a9026cad40df95f03096e1f7c400b8246a6ef57ee40297f79040945d3a41bf9e46c2942c

test:
  secret_key_base: 2b4a175320e6753a103b8be913041ac192d8e16185fc378d98ed15f088b0ffec30bdfd675ed6a7689074377532d7ff155441200775e3907949cfa165b35ba0a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
